config/routes.rb
Rails.application.routes.draw do
  resources :stats, only: [:index]
end

app/models/physical/division.rb
module Physical
  class Division < ActiveRecord::Base
    belongs_to :league

    validates :league_id, presence: true
    validates :name, presence: true, uniqueness: {
      scope: :league_id, case_sensitive: false
    }
  end
end

app/models/physical/league.rb
module Physical
  class League < ActiveRecord::Base
    has_many :seasons

    validates :name, presence: true, uniqueness: true
  end
end

app/models/physical/player.rb
module Physical
  class Player < ActiveRecord::Base
    belongs_to :team

    validates :avg, presence: true
    validates :at_bats, presence: true
    validates :caught_stealing, presence: true
    validates :doubles, presence: true
    validates :games, presence: true
    validates :games_started, presence: true
    validates :given_name, presence: true
    validates :hit_by_pitch, presence: true
    validates :hits, presence: true
    validates :home_runs, presence: true
    validates :ops, presence: true
    validates :pb, presence: true
    validates :player_errors, presence: true
    validates :position, presence: true
    validates :rbi, presence: true
    validates :runs, presence: true
    validates :sacrifice_flies, presence: true
    validates :sacrifice_hits, presence: true
    validates :steals, presence: true
    validates :struck_out, presence: true
    validates :surname, presence: true, uniqueness: {
      scope: [:given_name, :team_id], case_sensitive: false
    }
    validates :team_id, presence: true
    validates :triples, presence: true
    validates :walks, presence: true
  end
end

app/models/physical/season.rb
module Physical
  class Season < ActiveRecord::Base
    has_many :leagues

    validates :year, presence: true, uniqueness: true, case_sensitive: false
  end
end

app/models/physical/seasons_league.rb
module Physical
  class SeasonsLeague < ActiveRecord::Base
    belongs_to :league
    belongs_to :season
  end
end

app/models/physical/team.rb
module Physical
  class Team < ActiveRecord::Base
    belongs_to :division

    validates :city, presence: true
    validates :division_id, presence: true
    validates :name, presence: true, uniqueness: true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def index
    respond_to do |format|
      format.html
      format.json { render json: StatsDatatable.new(view_context) }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BaseballPlayerStats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Baseball Player Stats</h1>
  <%= yield %>
</body>
</html>

app/views/stats/index.html.erb
<table id="stats-table" class='foo' data-source="<%= stats_path(format: :json) %>">
  <thead>
    <tr>
      <th>Given Name</th>
      <th>Surname</th>
      <th>AVG</th>
      <th>HR</th>
      <th>RBI</th>
      <th>RUNS</th>
      <th>SB</th>
      <th>OPS</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>